name: linter
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  lint:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
      # run – произвольная bash-команда
      - run: make lint
